# Generated by Django 3.2.4 on 2021-06-16 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210614_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 20, 21, 39, 972207), verbose_name='Дата проведения'),
        ),
    ]
