# Generated by Django 3.2.4 on 2021-06-17 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_conference_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 2, 42, 53, 972516), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='requirements',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Требования'),
        ),
    ]
