# Generated by Django 3.2.4 on 2021-06-17 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210617_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='application',
            field=models.ManyToManyField(to='core.Conference'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 10, 6, 14, 96660), verbose_name='Дата проведения'),
        ),
    ]
