# Generated by Django 3.2.4 on 2021-06-17 10:19

import core.enums
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210617_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default=core.enums.StatusEnum['NEW'], max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 10, 19, 54, 899091), verbose_name='Дата проведения'),
        ),
    ]
