# Generated by Django 3.2.4 on 2021-06-17 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210617_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='НОВАЯ', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 4, 21, 534814), verbose_name='Дата проведения'),
        ),
    ]
