# Generated by Django 3.2.4 on 2021-06-17 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210617_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(upload_to='app_files', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='НА РАССМОТРЕНИИ', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 15, 13, 4, 458830), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='file',
            field=models.FileField(upload_to='conf_files', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images', verbose_name='Изображение'),
        ),
    ]
