# Generated by Django 3.2.4 on 2021-06-17 15:52

import datetime
from django.db import migrations, models
import django.template.context_processors


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210617_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(upload_to=django.template.context_processors.media, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 15, 52, 40, 504932), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='file',
            field=models.FileField(upload_to=django.template.context_processors.media, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=django.template.context_processors.media, verbose_name='Изображение'),
        ),
    ]
