# Generated by Django 3.2.4 on 2021-06-18 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210617_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='app_files', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 18, 20, 42, 38, 388822), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='conf_files', verbose_name='Вложения'),
        ),
    ]
