# Generated by Django 3.2.4 on 2021-06-19 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210618_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='count_participant',
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 12, 6, 34, 807126), verbose_name='Дата проведения'),
        ),
    ]
