# Generated by Django 3.2.4 on 2021-06-21 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210621_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(default='static/icons/smile.svg', upload_to='app_files', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 19, 51, 53, 695971), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='file',
            field=models.FileField(default='static/icons/smile.svg', upload_to='conf_files', verbose_name='Вложения'),
        ),
    ]
